# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI-Audio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI-Audio
  pod 'AgoraRtm_iOS', '~> 1.4'
  pod 'AgoraAudio_iOS', '~> 3.2'
end
